apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: docker-gs-ping
  name: docker-gs-ping
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-gs-ping
  template:
    metadata:
      labels:
        app: docker-gs-ping
    spec:
      containers:
        - image: rexwang/docker-gs-ping:v1
        name: docker-gs-ping
